/* global JSZip, PDFLib, pdfjsLib */
const AREA_ORDER = ["OPERACIONES MINA", "MALLA", "PLANEAMIENTO", "GEOMECANICA", "GEOLOGIA", "MANTENIMIENTO ELECTRICO", "VENTILACION", "SEGURIDAD / SSOMA", "GERENCIA OP."];
const ALIASES = {"OPERACIONES MINA":["MINA","OPERACIONES MINA","OPERACION MINA"],MALLA:["MALLA"],PLANEAMIENTO:["PLAN","PLANEAMIENTO"],GEOMECANICA:["GEOMEC","GEOMECANICA"],GEOLOGIA:["GEOL","GEOLOGIA"],"MANTENIMIENTO ELECTRICO":["MANT","MANTENIMIENTO","MANTENIMIENTO ELECTRICO"],VENTILACION:["VENT","VENTILACION"],"SEGURIDAD / SSOMA":["SSOMA","SEGURIDAD"],"GERENCIA OP.":["GERENCIA","GERENCIA OP","GERENCIA OPERACIONES","GERENCIA DE OPERACIONES"]};
const input=document.querySelector('#zipInput'), button=document.querySelector('#processButton'), logBox=document.querySelector('#log'), statusBox=document.querySelector('#status'), bar=document.querySelector('#progressBar');
let selectedZip;
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[_-]/g,' ').replace(/\s+/g,' ').trim();
function areaOf(folder){const n=norm(folder);for(const [area,names] of Object.entries(ALIASES)){if(names.some(a=>{a=norm(a);return n===a||n.startsWith(a+' ')||n.endsWith(' '+a)||n.includes(' '+a+' ')}))return area;}return null;}
function log(message,warning=false){logBox.textContent+=`${warning?'ALERTA: ':''}${message}\n`;logBox.scrollTop=logBox.scrollHeight;}
function progress(value,status){bar.style.width=`${value}%`;statusBox.textContent=status;}
function pdfEntries(zip){return Object.values(zip.files).filter(f=>!f.dir&&/\.pdf$/i.test(f.name));}
function dirsFromEntries(entries){const dirs=new Set(['']);for(const item of entries){const parts=item.name.split('/').slice(0,-1);for(let i=1;i<=parts.length;i++)dirs.add(parts.slice(0,i).join('/'));}return dirs;}
function directAreas(root,dirs){const prefix=root?root+'/':'';return [...dirs].filter(d=>d.startsWith(prefix)&&d.slice(prefix.length).indexOf('/')<0&&areaOf(d.slice(prefix.length)));}
function expedienteRoots(entries){const dirs=dirsFromEntries(entries);const roots=[...dirs].filter(d=>directAreas(d,dirs).length);return roots.sort((a,b)=>a.localeCompare(b));}
function isUnder(file,root){return root?file.name.startsWith(root+'/'):true;}
function coverFor(entries,root){const files=entries.filter(e=>isUnder(e,root));return files.find(e=>norm(e.name.split('/').pop().replace(/\.pdf$/i,'')).includes('CARATULA'))||files.find(e=>/^00/.test(e.name.split('/').pop()))||null;}
async function textOf(entry){const task=pdfjsLib.getDocument({data:await entry.async('uint8array')});const pdf=await task.promise;let text='';for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);text+=(await page.getTextContent()).items.map(x=>x.str).join(' ')+'\n';}return text;}
function expFrom(text,fallback){const m=text.match(/\bEXP\s*[-–—]?\s*\d+\b/i);return m?`EXP-${m[0].replace(/\D/g,'')}`:fallback;}
function companyFrom(text){const match=text.match(/COMPA(?:Ñ|N)IA\s*:?\s*(.+?)(?=\s+(?:TIPO|SUPERVISOR|LABOR|FECHA)\b|$)/i);return match&&match[1].trim();}
function companyFolder(text){const company=companyFrom(text);return company?company.toUpperCase().replace(/[<>:"/\\|?*]/g,'').replace(/\s+/g,' ').trim():"SIN_COMPANIA";}
function alerts(text,exp){for(const [area,names] of Object.entries(ALIASES)){const pattern=names.map(n=>norm(n).replace(/ /g,'\\s+')).join('|');const match=new RegExp(`(?:${pattern})\\s+(.{0,150}?)\\s+LISTO\\b`,'i').exec(norm(text));if(match&&/^[-\s]*$/.test(match[1]))log(`${exp} no cuenta con responsable en ${area==='SEGURIDAD / SSOMA'?'Seguridad (SSOMA)':area}`,true);}}
async function merge(entries){const output=await PDFLib.PDFDocument.create();for(const entry of entries){try{const source=await PDFLib.PDFDocument.load(await entry.async('arraybuffer'));const pages=await output.copyPages(source,source.getPageIndices());pages.forEach(p=>output.addPage(p));}catch(e){log(`No se pudo leer ${entry.name}: ${e.message}`,true);}}return output.save();}
function sortedFiles(entries,root,cover){const files=entries.filter(e=>isUnder(e,root));const result=[];if(cover)result.push(cover);for(const area of AREA_ORDER){const candidates=files.filter(e=>{const relative=root?e.name.slice(root.length+1):e.name;return areaOf(relative.split('/')[0])===area&&e!==cover;}).sort((a,b)=>a.name.localeCompare(b.name));result.push(...candidates);}return result;}
input.addEventListener('change',()=>{selectedZip=input.files[0];document.querySelector('#fileName').textContent=selectedZip?selectedZip.name:'Ningún ZIP seleccionado.';button.disabled=!selectedZip;});
button.addEventListener('click',async()=>{button.disabled=true;logBox.textContent='';try{progress(5,'Abriendo ZIP...');const zip=await JSZip.loadAsync(selectedZip);const entries=pdfEntries(zip),roots=expedienteRoots(entries),mode=document.querySelector('input[name="outputMode"]:checked').value;if(!roots.length)throw new Error('No se encontró una jerarquía de expediente con carpetas de áreas.');const resultZip=new JSZip();for(let i=0;i<roots.length;i++){const root=roots[i],cover=coverFor(entries,root);if(!cover){log(`No se encontró carátula en ${root||selectedZip.name}`,true);continue;}const text=await textOf(cover),folderName=root.split('/').pop()||selectedZip.name.replace(/\.zip$/i,'');const exp=/^EXP(?:[-_\s]|\d)/i.test(folderName)?folderName:expFrom(text,folderName);alerts(text,exp);const files=sortedFiles(entries,root,cover);if(!files.length){log(`No hay PDFs procesables para ${exp}`,true);continue;}const bytes=await merge(files);const target=mode==='company'?`${selectedZip.name.replace(/\.zip$/i,'')}_UNIDOS/${companyFolder(text)}/${exp}_UNIDO.pdf`:`${exp}_UNIDO.pdf`;resultZip.file(target,bytes);log(`Generado: ${target}`);progress(10+Math.round((i+1)/roots.length*80),`Procesando ${i+1} de ${roots.length} expedientes...`);}const blob=await resultZip.generateAsync({type:'blob'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${selectedZip.name.replace(/\.zip$/i,'')}_RESULTADO.zip`;a.click();URL.revokeObjectURL(a.href);progress(100,'Proceso terminado. Se descargó el resultado.');}catch(e){log(e.message||String(e),true);progress(0,'No se pudo completar el proceso.');}finally{button.disabled=false;}});
